resources:
- manager.yaml

images:
- name: controller
  newName: ghcr.io/nutanix-cloud-native/cluster-api-provider-nutanix/controller
  newTag: v0.2.0
- name: controller:latest
  newName: ghcr.io/nutanix-cloud-native/cluster-api-provider-nutanix/controller
  newTag: v0.2.0

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
